services:
  - type: web
    name: n8n-ffmpeg
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "U7sanems"
      - key: N8N_ENCRYPTION_KEY
        value: "b84f92b0138c78f5d1ac9c82ee30a777"
      - key: N8N_HOST
        value: "n8n-ffmpeg-0jy7.onrender.com"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_PORT
        value: "$PORT"
      - key: PORT
        value: "5678"
      - key: DB_TYPE
        value: "sqlite"
      - key: EXECUTIONS_PROCESS
        value: "main"
      - key: N8N_PATH
        value: "/home/node/.n8n"
